# permissions for end users to view hloadcores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hloadcore-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: hload
    app.kubernetes.io/part-of: hload
    app.kubernetes.io/managed-by: kustomize
  name: hloadcore-viewer-role
rules:
- apiGroups:
  - hload.hload.com
  resources:
  - hloadcores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hload.hload.com
  resources:
  - hloadcores/status
  verbs:
  - get
