---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - hload.hload.com
  resources:
  - hloadcores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hload.hload.com
  resources:
  - hloadcores/finalizers
  verbs:
  - update
- apiGroups:
  - hload.hload.com
  resources:
  - hloadcores/status
  verbs:
  - get
  - patch
  - update
